resource "openstatus_private_location" "eu_dc" {
  name        = "EU Datacenter"
  monitor_ids = [openstatus_http_monitor.api.id]

  metadata = {
    env    = "prod"
    region = "eu-west-1"
  }
}

# The agent token is generated by OpenStatus. Pass it to the checker agent.
output "agent_token" {
  value     = openstatus_private_location.eu_dc.token
  sensitive = true
}
