package privatelocation

import (
	"context"

	"terraform-provider-openstatus/internal/client"

	privatelocationv1 "buf.build/gen/go/openstatus/api/protocolbuffers/go/openstatus/private_location/v1"

	"connectrpc.com/connect"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var (
	_ resource.Resource                = (*privateLocationResource)(nil)
	_ resource.ResourceWithConfigure   = (*privateLocationResource)(nil)
	_ resource.ResourceWithImportState = (*privateLocationResource)(nil)
)

type providerConfig = client.ProviderConfig

func NewPrivateLocationResource() resource.Resource {
	return &privateLocationResource{}
}

type privateLocationResource struct {
	client *client.Client
}

type privateLocationModel struct {
	ID         types.String `tfsdk:"id"`
	Name       types.String `tfsdk:"name"`
	Token      types.String `tfsdk:"token"`
	MonitorIDs types.Set    `tfsdk:"monitor_ids"`
	Metadata   types.Map    `tfsdk:"metadata"`
	CreatedAt  types.String `tfsdk:"created_at"`
	UpdatedAt  types.String `tfsdk:"updated_at"`
}

func (r *privateLocationResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_private_location"
}

func (r *privateLocationResource) Configure(_ context.Context, req resource.ConfigureRequest, _ *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	r.client = req.ProviderData.(providerConfig).Client
}

func (r *privateLocationResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a private location: a self-hosted checker agent that runs the monitors you assign to it.\n\n" +
			"Terraform owns `monitor_ids` and `metadata`; removing either from the configuration clears it on the next apply. " +
			"Liveness (`status`, `last_seen_at`) is available on the `openstatus_private_location` data source.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"name": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Display name for the private location.",
				Validators:          []validator.String{stringvalidator.LengthBetween(1, 256)},
			},
			"monitor_ids": schema.SetAttribute{
				Optional:            true,
				ElementType:         types.StringType,
				MarkdownDescription: "IDs of the monitors this private location runs.",
			},
			"metadata": schema.MapAttribute{
				Optional:            true,
				ElementType:         types.StringType,
				MarkdownDescription: "User-defined key/value labels attached to this private location.",
			},
			"token": schema.StringAttribute{
				Computed:            true,
				Sensitive:           true,
				MarkdownDescription: "Agent credential generated by OpenStatus. Pass it to the agent to authenticate; treat it as a secret.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"created_at": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"updated_at": schema.StringAttribute{Computed: true},
		},
	}
}

func (r *privateLocationResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data privateLocationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	monitorIDs, metadata, diags := collectAssociations(ctx, data)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	apiReq := &privatelocationv1.CreatePrivateLocationRequest{}
	apiReq.SetName(data.Name.ValueString())
	apiReq.SetMonitorIds(monitorIDs)
	apiReq.SetMetadata(metadata)

	apiResp, err := r.client.PrivateLocation.CreatePrivateLocation(ctx, connect.NewRequest(apiReq))
	if err != nil {
		resp.Diagnostics.AddError("Error creating private location", err.Error())
		return
	}

	resp.Diagnostics.Append(privateLocationAPIToModel(ctx, apiResp.Msg.GetPrivateLocation(), &data)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *privateLocationResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data privateLocationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	getReq := &privatelocationv1.GetPrivateLocationRequest{}
	getReq.SetId(data.ID.ValueString())

	apiResp, err := r.client.PrivateLocation.GetPrivateLocation(ctx, connect.NewRequest(getReq))
	if err != nil {
		if client.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading private location", err.Error())
		return
	}

	resp.Diagnostics.Append(privateLocationAPIToModel(ctx, apiResp.Msg.GetPrivateLocation(), &data)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *privateLocationResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data privateLocationModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var state privateLocationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	monitorIDs, metadata, diags := collectAssociations(ctx, data)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	updateReq := newUpdateRequest(state.ID.ValueString(), data.Name.ValueString(), monitorIDs, metadata)

	apiResp, err := r.client.PrivateLocation.UpdatePrivateLocation(ctx, connect.NewRequest(updateReq))
	if err != nil {
		resp.Diagnostics.AddError("Error updating private location", err.Error())
		return
	}

	resp.Diagnostics.Append(privateLocationAPIToModel(ctx, apiResp.Msg.GetPrivateLocation(), &data)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *privateLocationResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data privateLocationModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	deleteReq := &privatelocationv1.DeletePrivateLocationRequest{}
	deleteReq.SetId(data.ID.ValueString())

	_, err := r.client.PrivateLocation.DeletePrivateLocation(ctx, connect.NewRequest(deleteReq))
	if err != nil && !client.IsNotFound(err) {
		resp.Diagnostics.AddError("Error deleting private location", err.Error())
	}
}

func (r *privateLocationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), types.StringValue(req.ID))...)
}

func collectAssociations(ctx context.Context, data privateLocationModel) ([]string, map[string]string, diag.Diagnostics) {
	var diags diag.Diagnostics

	monitorIDs := []string{}
	if !data.MonitorIDs.IsNull() && !data.MonitorIDs.IsUnknown() {
		diags.Append(data.MonitorIDs.ElementsAs(ctx, &monitorIDs, false)...)
	}

	metadata := map[string]string{}
	if !data.Metadata.IsNull() && !data.Metadata.IsUnknown() {
		diags.Append(data.Metadata.ElementsAs(ctx, &metadata, false)...)
	}

	return monitorIDs, metadata, diags
}

// newUpdateRequest always sets the update_* sentinels so Terraform stays
// authoritative: without them the API preserves whatever it already has,
// and removing a monitor or label from the configuration would never apply.
func newUpdateRequest(id, name string, monitorIDs []string, metadata map[string]string) *privatelocationv1.UpdatePrivateLocationRequest {
	req := &privatelocationv1.UpdatePrivateLocationRequest{}
	req.SetId(id)
	req.SetName(name)
	req.SetMonitorIds(monitorIDs)
	req.SetUpdateMonitorIds(true)
	req.SetMetadata(metadata)
	req.SetUpdateMetadata(true)
	return req
}

func privateLocationAPIToModel(ctx context.Context, api *privatelocationv1.PrivateLocation, data *privateLocationModel) diag.Diagnostics {
	var diags diag.Diagnostics

	data.ID = types.StringValue(api.GetId())
	data.Name = types.StringValue(api.GetName())
	data.Token = types.StringValue(api.GetToken())
	data.CreatedAt = types.StringValue(api.GetCreatedAt())
	data.UpdatedAt = types.StringValue(api.GetUpdatedAt())

	if len(api.GetMonitorIds()) > 0 {
		set, d := types.SetValueFrom(ctx, types.StringType, api.GetMonitorIds())
		diags.Append(d...)
		data.MonitorIDs = set
	} else {
		data.MonitorIDs = types.SetNull(types.StringType)
	}

	if len(api.GetMetadata()) > 0 {
		m, d := types.MapValueFrom(ctx, types.StringType, api.GetMetadata())
		diags.Append(d...)
		data.Metadata = m
	} else {
		data.Metadata = types.MapNull(types.StringType)
	}

	return diags
}
